USER_LANGUAGE=en
USER_NO_STOP=y
USER_INSTALL_TYPE=agent
USER_DIR=/var/ossec
USER_DELETE_DIR=y
USER_CLEANINSTALL=y
USER_BINARYINSTALL=y
USER_AGENT_SERVER_IP=MANAGER_IP
USER_ENABLE_SYSCHECK=y
USER_ENABLE_ROOTCHECK=y
USER_ENABLE_OPENSCAP=n
USER_ENABLE_CISCAT=n
USER_ENABLE_ACTIVE_RESPONSE=y
USER_CA_STORE=n
