#!/sbin/runscript
# Gentoo init script
# Copyright (C) 2015, Verprotect Inc.
# by gentuxx <gentuxx@gmail.com>

opts="${opts} status configtest"

VERPROTECT_HOME=VERPROTECT_HOME_TMP
VERPROTECT_CONTROL="$VERPROTECT_HOME/bin/verprotect-control"

depend() {
    need net
    use logger
}

configtest() {
    ebegin "Checking Verprotect Configuration"
    checkconfig
    eend $?
}

checkconfig() {
    CONFIGFILE="${CONFIGFILE:-$VERPROTECT_HOME/etc/ossec.conf}"
    if [ ! -r "${CONFIGFILE}" ]; then
        eerror "Unable to read configuration file: ${CONFIGFILE}"
        return 1
    fi

    # Maybe put some kind of config file syntax checking in here?  XML is a little different
    # so maybe not.
    return $ret
}

start() {
    checkconfig || return 1
    ebegin "Starting Verprotect"
    ${VERPROTECT_CONTROL} start > /dev/null 2>&1
    eend $?
}

stop() {
    checkconfig || return 1
    ebegin "Stopping Verprotect"
    ${VERPROTECT_CONTROL} stop > /dev/null 2>&1
    eend $?
}

restart() {
    if ! service_started "${myservice}" ; then
        eerror "Verprotect is not running! Please start it before trying to reload it."
    else
        checkconfig || return 1
        ebegin "Reloading Verprotect"
        svc_stop ${VERPROTECT_CONTROL}
        svc_start ${VERPROTECT_CONTROL}
        eend $?
    fi
}

status() {
    checkconfig || return 1
    ${VERPROTECT_CONTROL} status
}
