#!/bin/sh

# Copyright (C) 2015, Verprotect Inc.
# OSSEC         Controls Verprotect on Redhat-based systems
# Author:       Kayvan A. Sylvan <kayvan@sylvan.com>
# Author:       Daniel B. Cid <dcid@ossec.net>
#
# chkconfig: 2345 99 15
# description: Starts and stops Verprotect (Host Intrusion Detection System)
#
# This will work on Redhat systems (maybe others too)

# Source function library.
export LANG=C

. /etc/init.d/functions

VERPROTECT_HOME=VERPROTECT_HOME_TMP
VERPROTECT_CONTROL="$VERPROTECT_HOME/bin/verprotect-control"

start() {
    echo -n "Starting Verprotect: "
    ${VERPROTECT_CONTROL} start > /dev/null
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
        success
    else
        failure
    fi
    echo
    return $RETVAL
}

stop() {
    echo -n "Stopping Verprotect: "
    ${VERPROTECT_CONTROL} stop > /dev/null
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
        success
    else
        failure
    fi
    echo
    return $RETVAL
}

status() {
    ${VERPROTECT_CONTROL} status
    RETVAL=$?
    return $RETVAL
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    stop
    start
    ;;
status)
    status
    ;;
*)
    echo "*** Usage: ossec {start|stop|restart|status}"
    exit 1
esac

exit $?
