#!/bin/sh
#
# name: wazuh
# purpose: Init script for Verprotect
# Copyright (C) 2015, Verprotect Inc. <support@wazuh.com>
#

VERPROTECT_HOME=VERPROTECT_HOME_TMP
VERPROTECT_CONTROL="$VERPROTECT_HOME/bin/verprotect-control"

case "$1" in
start)
    if [ -f "$VERPROTECT_CONTROL" ]; then
        echo "Starting Verprotect"
        ${VERPROTECT_CONTROL} start
    fi
    ;;
stop)
    if [ -f "$VERPROTECT_CONTROL" ]; then
        echo "Stopping Verprotect"
        ${VERPROTECT_CONTROL} stop
    fi
    ;;
status)
    if [ -f "$VERPROTECT_CONTROL" ]; then
        ${VERPROTECT_CONTROL} status
    fi
    ;;
restart)
    if [ -f "$VERPROTECT_CONTROL" ]; then
        ${VERPROTECT_CONTROL} restart
    fi
    ;;
*)
    echo "Usage: $0 (start | stop | restart | status)"
    exit 1
esac
