#!/bin/sh

# Copyright (C) 2015, Verprotect Inc.
# OSSEC         Controls Verprotect
# Author:       Daniel B. Cid <dcid@ossec.net>
# Modified for Debian by Michael Starks (patch by Costas Drogos)

### BEGIN INIT INFO
# Provides:          ossec
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      $network
# Should-Stop:       $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop Verprotect
# Description:       Controls Verprotect daemons
#
### END INIT INFO

VERPROTECT_HOME=VERPROTECT_HOME_TMP
VERPROTECT_CONTROL="$VERPROTECT_HOME/bin/verprotect-control"

start() {
    ${VERPROTECT_CONTROL} start
}

stop() {
    ${VERPROTECT_CONTROL} stop
}

status() {
    ${VERPROTECT_CONTROL} status
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    stop
    start
    ;;
status)
    status
    ;;
*)
    echo "*** Usage: $0 {start|stop|restart|status}"
    exit 1
esac
