#!/bin/sh

# Copyright (C) 2015, Verprotect Inc.
# OSSEC         Controls Verprotect
# Author:       Daniel B. Cid <dcid@ossec.net>
# Modified for slackware by Jack S. Lai

VERPROTECT_HOME=VERPROTECT_HOME_TMP
VERPROTECT_CONTROL="$VERPROTECT_HOME/bin/verprotect-control"

start() {
    ${VERPROTECT_CONTROL} start
}

stop() {
    ${VERPROTECT_CONTROL} stop
}

status() {
    ${VERPROTECT_CONTROL} status
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    stop
    start
    ;;
status)
    status
    ;;
*)
    echo "*** Usage: $0 {start|stop|restart|status}"
    exit 1
esac

exit 0
